# Generated by Django 5.1.1 on 2024-09-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hairdressers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hairdresser",
            name="experience_years",
        ),
        migrations.AddField(
            model_name="hairdresser",
            name="availability",
            field=models.CharField(default="9 AM - 6 PM", max_length=100),
        ),
        migrations.AddField(
            model_name="hairdresser",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="hairdresser",
            name="email",
            field=models.EmailField(default="default@example.com", max_length=254),
        ),
        migrations.AddField(
            model_name="hairdresser",
            name="experience",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="hairdresser",
            name="name",
            field=models.CharField(default="Default Name", max_length=100),
        ),
        migrations.AddField(
            model_name="hairdresser",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="hairdresser",
            name="specialization",
            field=models.CharField(default="General Hairdresser", max_length=100),
        ),
    ]
