# Generated by Django 5.1.1 on 2024-09-10 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hairdressers", "0002_remove_hairdresser_experience_years_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="hairdresser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hairdresser_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
