# Generated by Django 5.1.1 on 2024-09-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="email",
            field=models.EmailField(default="default@example.com", max_length=254),
        ),
        migrations.AddField(
            model_name="client",
            name="name",
            field=models.CharField(default="Default Client Name", max_length=100),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
