# Generated by Django 5.1.1 on 2024-09-04 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("hairdressers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service", models.CharField(max_length=100)),
                ("date_time", models.DateTimeField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clients.client"
                    ),
                ),
                (
                    "hairdresser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hairdressers.hairdresser",
                    ),
                ),
            ],
        ),
    ]
