# Generated by Django 5.1.1 on 2024-09-08 08:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="appointment",
            name="end_time",
            field=models.TimeField(default="12:00:00"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="start_time",
            field=models.TimeField(default="09:00:00"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.CharField(
                choices=[
                    ("стрижка", "Стрижка"),
                    ("покраска", "Покраска"),
                    ("маникюр", "Маникюр"),
                ],
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="appointment",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="appointments.client",
            ),
        ),
        migrations.CreateModel(
            name="Hairdresser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specialization", models.CharField(max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hairdresser_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="appointment",
            name="hairdresser",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="appointments.hairdresser",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={("hairdresser", "date", "start_time")},
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="date_time",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="notes",
        ),
    ]
