# Generated by Django 5.1.1 on 2024-09-08 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0002_appointment_date_appointment_end_time_and_more"),
        ("clients", "0003_alter_client_user"),
        ("hairdressers", "0002_remove_hairdresser_experience_years_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="clients.client",
            ),
        ),
        migrations.RemoveField(
            model_name="hairdresser",
            name="user",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="hairdresser",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="hairdressers.hairdresser",
            ),
        ),
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.DeleteModel(
            name="Hairdresser",
        ),
    ]
