# Generated by Django 5.1.1 on 2024-09-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "appointments",
            "0003_alter_appointment_client_remove_hairdresser_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="end_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.CharField(
                choices=[
                    ("haircut", "Haircut"),
                    ("coloring", "Coloring"),
                    ("manicure", "Manicure"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="start_time",
            field=models.TimeField(),
        ),
    ]
