# Generated by Django 5.1.1 on 2024-10-05 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0004_alter_appointment_unique_together_and_more"),
        ("clients", "0003_alter_client_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="clients.client",
            ),
        ),
    ]
